version: '3'

services:
  db:
    container_name: MySQL
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}

  wordpress:
    container_name: WordPress
    depends_on:
      - db
    image: wordpress:latest
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: ${DB_NAME}
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./src:/var/www/html

  nginx:
    container_name: Nginx
    image: nginx:latest
    volumes:
      - ./src:/var/www/html
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - wordpress

  certbot:
    container_name: Certbot
    image: certbot/certbot
    volumes:
      - ./src:/var/www/html
      - /.docker/etc/letsencrypt:/etc/letsencrypt
    command: certonly --webroot -w /var/www/html -d ${NGINX_DOMAIN} --agree-tos --email ${EMAIL} --no-eff-email --force-renewal

volumes:
  db_data: